# Generated by Django 5.0.2 on 2025-06-05 12:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bsmapp', '0002_about_uzmanlarimiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='desc2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
