# Generated by Django 5.0.2 on 2025-06-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsmapp', '0004_service_anasayfa'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('icon', models.CharField(max_length=255)),
            ],
        ),
    ]
